version: 2.1
jobs:
  build:
   docker:
      - image: ubuntu:18.04
   steps:
      - run:
          name: "Dump"
          command: |
            apt-get update -y && apt-get upgrade -y && apt install unace unrar zip unzip p7zip-full p7zip-rar sharutils rar uudeview mpack arj cabextract device-tree-compiler liblzma-dev python3-pip brotli liblz4-tool axel gawk aria2 detox cpio rename liblz4-dev curl -y
            git clone --single-branch https://github.com/DumprX/DumprX.git
            cd DumprX
            ./dumper.sh 'https://drive.google.com/file/d/1OI9XhtdVsdqxQG-hBziwYD3LsECgoVoc/view'
            
workflows:
  version: 2.1
  remote_builder:
    jobs:
      - build:
          context: org-global

