version: 2.1
jobs:
  build:
   docker:
      - image: ubuntu:20.04
   environment:
      URL: "https://drive.google.com/file/d/1OI9XhtdVsdqxQG-hBziwYD3LsECgoVoc/view"
      FIRMWARE_NAME: "TECNO-KE6"
      VENDOR_NAME: "TECNO"
      

   
   steps:
      - run:
          name: "dumprX"
          command: |
            apt-get update -y && apt-get upgrade -y && apt-get install wget curl git zip unzip gcc build-essential bc sudo python3 python3-pip -y
            sudo apt install unace unrar zip unzip p7zip-full p7zip-rar sharutils rar uudeview mpack arj cabextract rename -y
            sudo apt install liblzma-dev python3-pip brotli lz4 -y
            pip install backports.lzma protobuf pycrypto twrpdtgen extract-dtb 
            export DEBIAN_FRONTEND=noninteractive
            apt-get install tzdata -y
            
            git config --global user.name "test"
            git config --global user.email "test@gmail.com"
            
     
            mkdir workspace
            cd workspace
            git clone https://github.com/cd-Crypton/DumprX.git
            cd DumprX
            sudo bash setup.sh
            ./dumper.sh ${URL}
            
            
            git init
            git add .
            git commit -m "first commit"
            git branch -M main
            git remote add origin https://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@github.com/dhruvtadvitest/tecn0
            git push -u origin main

            
            


