version: 2.1
jobs:
  build:
   docker:
      - image: ubuntu:20.04
   steps:
      - run:
          name: "environment setup"
          command: |
            apt update -y && apt upgrade -y && apt install sudo -y
            sudo apt install unace unrar zip unzip p7zip-full p7zip-rar sharutils rar uudeview mpack arj cabextract rename
            sudo apt install liblzma-dev python3-pip brotli lz4
            pip install backports.lzma protobuf pycrypto twrpdtgen extract-dtb pycryptodom
            
     
            mkdir workspace
            cd workspace
            git clone https://github.com/cd-Crypton/DumprX.git
            cd DumprX
            sudo bash setup.sh
            
   
            ./dumper.sh 'https://drive.google.com/file/d/1OI9XhtdVsdqxQG-hBziwYD3LsECgoVoc/view'
            


